version: '3.8'
services:
  static:
    image: nginx:1.19.2
    volumes:
      - "build:/usr/share/nginx/another"
      - "${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "5001:80"
    links:
      - node
    depends_on:
      - react
  node:
    build: ./node
    environment:
      - NODE_ENV=development
      - NODEJS_PORT=3001
      - REDIS_URL=redis://redis
    volumes:
      - "./node:/home/node/app/"
      - "be-node-modules:/home/node/app/node_modules/"
    links:
      - redis
    ports:
      - "3001:3001"
    depends_on:
      - redis
  react:
    build: ./react
    volumes:
      - "build:/home/node/app/dist"
      - "./react:/home/node/app/"
      - "fe-node-modules:/home/node/app/node_modules/"
    ports:
      - "5173:5173"
    links:
      - node
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379

volumes:
  build:
  be-node-modules:
  fe-node-modules: